### ISSUE TITLE
Keras training

### ISSUE THREAD

**Issue by Matanpugach** [guxd/deep-code-search#11]
Hello,

While training the keras module i get the following issue:
```
Epoch 1 ::
Train on 80000 samples, validate on 20000 samples
Epoch 1/1
Traceback (most recent call last):
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'desc' with dtype int32 and shape [?,30]
         [[Node: desc = Placeholder[dtype=DT_INT32, shape=[?,30], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "codesearcher.py", line 429, in <module>
    codesearcher.train(model)
  File "codesearcher.py", line 209, in train
    hist = model.fit([chunk_padded_methnames,chunk_padded_apiseqs,chunk_padded_tokens, chunk_padded_good_descs, chunk_padded_bad_descs], epochs=1, batch_size=batch_size, validation_split=split)
  File "/home-local/matan.pugach/deep-code-search/keras/models.py", line 225, in fit
    return self._training_model.fit(x, y, **kwargs)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1485, in fit
    initial_epoch=initial_epoch)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1140, in _fit_loop
    outs = f(ins_batch)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2075, in __call__
    feed_dict=feed_dict)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'desc' with dtype int32 and shape [?,30]
         [[Node: desc = Placeholder[dtype=DT_INT32, shape=[?,30], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'desc', defined at:
  File "codesearcher.py", line 424, in <module>
    model.build()
  File "/home-local/matan.pugach/deep-code-search/keras/models.py", line 146, in build
    desc = Input(shape=(self.data_params['desc_len'],), dtype='int32', name='desc')
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/keras/engine/topology.py", line 1375, in Input
    input_tensor=tensor)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/keras/engine/topology.py", line 1286, in __init__
    name=self.name)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 349, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1777, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4521, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/home/matan.pugach/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'desc' with dtype int32 and shape [?,30]
         [[Node: desc = Placeholder[dtype=DT_INT32, shape=[?,30], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

I have installed all packages according to the requirements.

**Comment by guxd** [comment]
We never met such an error. According to the exception trace, the tensorflow requires the placeholder 'desc'. Did you check whether all required inputs are valid and fed into the model?

**Comment by Matanpugach** [comment]
@guxd i just rerun the model using the most recent data from google drive, unrar-ed and un7zip-ped, in \data\github and got the same error. Are there any other special instructions? Params need to edited? 
Regarding the error - when should a placeholder be fed? the creation line is
[desc = Input(shape=(self.data_params['desc_len'],), dtype='int32', name='desc')](url)

**Comment by guxd** [comment]
There is no special instruction. Maybe it is due to your personal environment. Could you print the intermediate value of desc that is fed to the model?

**Comment by Matanpugach** [comment]
Assuming you know the code better, where do you suggest i add the print instruction?

**Comment by Matanpugach** [comment]
the descriptions are:
```
chunk_padded_good_descs: (of shape (100000, 30)
[[  21  132    6 ...    0    0    0]
 [  25   10   40 ...    0    0    0]
 [   6   27 1186 ...    0    0    0]
 ...
 [   7    2    1 ...    0    0    0]
 [  38   17   71 ...    0    0    0]
 [  25    3 1229 ...    0    0    0]]
chunk_padded_bad_descs: (of shape (100000, 30)
[[ 375    2  995 ...    0    0    0]
 [ 259  193  479 ...    0    0    0]
 [  15    2 1470 ...    0    0    0]
 ...
 [   7    3   28 ...    0    0    0]
 [  21    2 7188 ...    0    0    0]
 [  15    2  508 ...    0    0    0]]
`
the other params are:`
chunk_padded_methnames: (of shape (100000, 6)
[[ 468 1708    0    0    0    0]
 [   6 5763 4356 3522 2365  463]
 [  57    0    0    0    0    0]
 ...
 [   2    1   23   20    0    0]
 [   7    3  179    0    0    0]
 [ 157   19    0    0    0    0]]
chunk_padded_apiseqs: (of shape (100000, 30)
[[  9   5 281 ...   0   0   0]
 [105   2   0 ...   0   0   0]
 [639  37 639 ...   0   0   0]
 ...
 [  7  21   7 ...   0   0   0]
 [288  10   0 ...   0   0   0]
 [ 34  58  34 ...   0   0   0]]
chunk_padded_tokens: (of shape (100000, 50)
[[ 869 1278   15 ...    0    0    0]
 [ 135 6558  106 ...    0    0    0]
 [ 388  193   19 ...    0    0    0]
 ...
 [  15    1    2 ...    0    0    0]
 [1909    2  136 ...    0    0    0]
 [  21   12   68 ...    0    0    0]]
```

**Comment by Matanpugach** [comment]
@guxd thank you for your support& patience ! 
I think i solved it for now. Thanks! for future reference, the issue was my keras version was 2.0.0 according to the requirements but When i updated to 2.0.5 the exception was not thrown 😄
