### ISSUE TITLE
InvalidArgumentError: Shape [-1,30] has negative dimensions 	 [[Node: desc = Placeholder[dtype=DT_INT32, shape=[?,30], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

### ISSUE THREAD

**Issue by siyuan13180892817** [guxd/deep-code-search#37]
训练的时候报这个错是怎么回事。 为什么会显示没fed那个desc中数据啊。
具体报错如下：
2019-09-09 09:18:56.138512: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1148] Invalid argument: Shape [-1,30] has negative dimensions
2019-09-09 09:18:56.138757: E c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\common_runtime\executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1,30] has negative dimensions
	 [[Node: desc = Placeholder[dtype=DT_INT32, shape=[?,30], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Traceback (most recent call last):
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
  File "D:\anaconda\installs\envs\tensorflow\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape [-1,30] has negative dimensions
	 [[Node: desc = Placeholder[dtype=DT_INT32, shape=[?,30], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/pycharm/workplaces/prac/deep-code-search-master/keras/main.py", line 457, in <module>
    codesearcher.train(model)
  File "D:/pycharm/workplaces/prac/deep-code-search-master/keras/main.py", line 228, in train
    hist = model.fit([chunk_padded_methnames,chunk_padded_apiseqs,chunk_padded_tokens,chunk_padded_good_descs,chunk_padded_bad_descs], epochs=10, batch_size=batch_size, validation_split=split)
  File "D:\pycharm\workplaces\prac\deep-code-search-master\keras\models.py", line 227, in fit
    return self._training_model.fit(x, y, **kwargs)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1485, in fit
    initial_epoch=initial_epoch)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1140, in _fit_loop
    outs = f(ins_batch)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py", line 2075, in __call__
    feed_dict=feed_dict)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape [-1,30] has negative dimensions
	 [[Node: desc = Placeholder[dtype=DT_INT32, shape=[?,30], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'desc', defined at:
  File "D:/pycharm/workplaces/prac/deep-code-search-master/keras/main.py", line 452, in <module>
    model.build()
  File "D:\pycharm\workplaces\prac\deep-code-search-master\keras\models.py", line 144, in build
    desc = Input(shape=(self.data_params['desc_len'],), dtype='int32', name='desc')
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\keras\engine\topology.py", line 1375, in Input
    input_tensor=tensor)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\keras\engine\topology.py", line 1286, in __init__
    name=self.name)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py", line 349, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1530, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1954, in _placeholder
    name=name)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\anaconda\installs\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Shape [-1,30] has negative dimensions
	 [[Node: desc = Placeholder[dtype=DT_INT32, shape=[?,30], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Process finished with exit code 1

**Comment by guxd** [comment]
It is probably due to the tensorflow-windows you use. We will test tensorflow-windows, but could you try using Linux for the training?

**Comment by siyuan13180892817** [comment]
@

> It is probably due to the tensorflow-windows you use. We will test tensorflow-windows, but could you try using Linux for the training?

在linux系统训练的时候报错和这个差不多，都是desc的数据未填充    数据的格式都是正确的  看了好多遍代码，没找到哪里的问题。 

x是指model.fit([chunk_padded_methnames,chunk_padded_apiseqs,chunk_padded_tokens,chunk_padded_good_descs,chunk_padded_bad_descs], epochs=10, batch_size=batch_size, validation_split=split)
y是np.zeros(shape=x[0].shape[:1],dtype=np.float32)
在model.fit函数里生成的y是什么原理呢？ 

刚才那个问题在linux报错如下:
Train on 80000 samples, validate on 20000 samples
Epoch 1/10
Traceback (most recent call last):
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'desc' with dtype int32 and shape [?,30]
	 [[{{node desc}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 457, in <module>
    codesearcher.train(model)
  File "main.py", line 228, in train
    hist = model.fit([chunk_padded_methnames,chunk_padded_apiseqs,chunk_padded_tokens,chunk_padded_good_descs,chunk_padded_bad_descs], epochs=10, batch_size=batch_siz
e, validation_split=split)  File "/home/hsy/deepCodeSearch/deep-code-search-master/keras/models.py", line 227, in fit
    return self._training_model.fit(x, y, **kwargs)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/training.py", line 1485, in fit
    initial_epoch=initial_epoch)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/training.py", line 1140, in _fit_loop
    outs = f(ins_batch)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2075, in __call__
    feed_dict=feed_dict)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'desc' with dtype int32 and shape [?,30]
	 [[node desc (defined at /home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:349) ]]

Original stack trace for 'desc':
  File "main.py", line 452, in <module>
    model.build()
  File "/home/hsy/deepCodeSearch/deep-code-search-master/keras/models.py", line 144, in build
    desc = Input(shape=(self.data_params['desc_len'],), dtype='int32', name='desc')
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/topology.py", line 1375, in Input
    input_tensor=tensor)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/topology.py", line 1286, in __init__
    name=self.name)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 349, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 2143, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6262, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/hsy/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by guxd** [comment]
代码有更新，你可以重试一下
