### ISSUE TITLE
NameError: name 'F' is not defined

### ISSUE THREAD

**Issue by Laksh47** [guxd/deep-code-search#5]
Hi, @guxd 

I just replicated the repo and ran it on the data available in the repo! I ran into this error!

```
larumuga@scspc743:~/workspace/deep-code-search/pytorch$ python codesearcher.py --mode train
Build Model
/home/larumuga/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
loading data...
10000 entries
/home/larumuga/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:995: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
epo:[0/2000] itr:100 Loss=0.05644
epo:[0/2000] itr:200 Loss=0.05123
epo:[0/2000] itr:300 Loss=0.04307
epo:[0/2000] itr:400 Loss=0.03867
epo:[0/2000] itr:500 Loss=0.03428
epo:[0/2000] itr:600 Loss=0.03314
epo:[0/2000] itr:700 Loss=0.03253
epo:[0/2000] itr:800 Loss=0.03131
epo:[1/2000] itr:100 Loss=0.02819
epo:[1/2000] itr:200 Loss=0.02607
epo:[1/2000] itr:300 Loss=0.02635
epo:[1/2000] itr:400 Loss=0.02651
epo:[1/2000] itr:500 Loss=0.02542
epo:[1/2000] itr:600 Loss=0.02513
epo:[1/2000] itr:700 Loss=0.02473
epo:[1/2000] itr:800 Loss=0.02718
epo:[2/2000] itr:100 Loss=0.02327
epo:[2/2000] itr:200 Loss=0.01982
epo:[2/2000] itr:300 Loss=0.02143
epo:[2/2000] itr:400 Loss=0.02162
epo:[2/2000] itr:500 Loss=0.02315
epo:[2/2000] itr:600 Loss=0.02130
epo:[2/2000] itr:700 Loss=0.01996
epo:[2/2000] itr:800 Loss=0.02273
epo:[3/2000] itr:100 Loss=0.01937
epo:[3/2000] itr:200 Loss=0.02110
epo:[3/2000] itr:300 Loss=0.01906
epo:[3/2000] itr:400 Loss=0.01828
epo:[3/2000] itr:500 Loss=0.01787
epo:[3/2000] itr:600 Loss=0.01970
epo:[3/2000] itr:700 Loss=0.01939
epo:[3/2000] itr:800 Loss=0.02107
epo:[4/2000] itr:100 Loss=0.01615
epo:[4/2000] itr:200 Loss=0.01669
epo:[4/2000] itr:300 Loss=0.01728
epo:[4/2000] itr:400 Loss=0.01682
epo:[4/2000] itr:500 Loss=0.01564
epo:[4/2000] itr:600 Loss=0.01815
epo:[4/2000] itr:700 Loss=0.01740
epo:[4/2000] itr:800 Loss=0.01807
epo:[5/2000] itr:100 Loss=0.01421
epo:[5/2000] itr:200 Loss=0.01602
epo:[5/2000] itr:300 Loss=0.01493
epo:[5/2000] itr:400 Loss=0.01675
epo:[5/2000] itr:500 Loss=0.01464
epo:[5/2000] itr:600 Loss=0.01737
epo:[5/2000] itr:700 Loss=0.01627
epo:[5/2000] itr:800 Loss=0.01482
loading data...
10000 entries
Traceback (most recent call last):
  File "codesearcher.py", line 290, in <module>
    searcher.train(model)
  File "codesearcher.py", line 116, in train
    acc1, mrr = self.eval(model,1000,1)              
  File "codesearcher.py", line 193, in eval
    sims = F.cosine_similarity(code_repr, desc_repr).data.cpu().numpy()
NameError: name 'F' is not defined
Closing remaining open files:./data/github/test.desc.h5...done./data/github/test.tokens.h5...done./data/github/test.methname.h5...done./data/github/train.apiseq.h5...done./data/github/test.apiseq.h5...done./data/github/train.tokens.h5...done./data/github/train.methname.h5...done./data/github/train.desc.h5...done
larumuga@scspc743:~/workspace/deep-code-search/pytorch$ 

```

**Comment by guxd** [comment]
I fixed the bug in the latest commit. Please check it out.
