### ISSUE TITLE
Issue Loading Data - What should I do to fix the error?

### ISSUE THREAD

**Issue by tejshahresearch** [guxd/deep-code-search#67]
When I load in the data via `python repr_code.py -t 202106140524 --reload_from 4000000`

I get this error. What should I do to fix the error? 

```
done
 87%|███████████████████████████████████████████████████████████▎        | 1419/1627 [20:42<03:02,  1.14it/s]
Traceback (most recent call last):
  File "repr_code.py", line 73, in <module>
    repr_code(args)
  File "repr_code.py", line 50, in repr_code
    save_vecs(np.vstack(vecs), output_path)
  File "/common/home/tps75/deep-code-search/pytorch/data_loader.py", line 106, in save_vecs
    fvec = tables.open_file(fout, 'w')
  File "/common/home/tps75/miniconda3/lib/python3.8/site-packages/tables/file.py", line 315, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/common/home/tps75/miniconda3/lib/python3.8/site-packages/tables/file.py", line 778, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 444, in H5Fcreate
    unable to create file
  File "H5Fint.c", line 1364, in H5F__create
    unable to open file
  File "H5Fint.c", line 1557, in H5F_open
    unable to open file: time = Fri Oct 15 20:28:30 2021
, name = './data/github/use.codevecs_part70.h5', tent_flags = 13
  File "H5FD.c", line 734, in H5FD_open
    open failed
  File "H5FDsec2.c", line 346, in H5FD_sec2_open
    unable to open file: name = './data/github/use.codevecs_part70.h5', errno = 122, error message = 'Disk quota exceeded', flags = 13, o_flags = 242

End of HDF5 error back trace

Unable to open/create file './data/github/use.codevecs_part70.h5'
Closing remaining open files:./data/github/use.name.h5...done./data/github/use.tokens.h5...done./data/github/use.apiseq.h5...done
```

**Comment by saicharishmavalluri** [comment]
Hello @tejshahresearch,
May I know how your ETA is 20 minutes, while my ETA shows 25 hours for pre-trained model. I am using Google Colaboratory to run the tool. 

-- Sai
