### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for JointEmbeder:

### ISSUE THREAD

**Issue by SIPUNK** [guxd/deep-code-search#77]
I re-partition and train the CSN dataset, when I test the trained model, I get the following error, how to fix it：
``` 
   Traceback (most recent call last):
  File "train.py", line 385, in <module>
    test(args)
  File "train.py", line 327, in test
    'JointEmbeder/github/models/step310000.h5', map_location=device))
  File "/home/abc/anaconda3/envs/deep_code_search/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for JointEmbeder:
        size mismatch for name_encoder.embedding.weight: copying a param with shape torch.Size([18869, 256]) from checkpoint, the shape in current model is torch.Size([19265, 256]).
        size mismatch for api_encoder.embedding.weight: copying a param with shape torch.Size([666421, 256]) from checkpoint, the shape in current model is torch.Size([695106, 256]).
        size mismatch for tok_encoder.embedding.weight: copying a param with shape torch.Size([183369, 256]) from checkpoint, the shape in current model is torch.Size([189488, 256]).
        size mismatch for desc_encoder.embedding.weight: copying a param with shape torch.Size([40338, 256]) from checkpoint, the shape in current model is torch.Size([41353, 256]).
```

**Comment by SIPUNK** [comment]
help!!!!!

**Comment by guxd** [comment]
Which line throws the error? I checked the `train.py` in the Pytorch version, which does not have Line 385.

**Comment by SIPUNK** [comment]
> Which line throws the error? I checked the `train.py` in the Pytorch version, which does not have Line 385.

Thanks for your reply, I found a problem with the model training and fixed it
